---
sudo: required

services:
  - docker

language: ruby

bundler_args: --without development

rvm:
  - 2.0.0
script: 
  - bundle exec rake test
  - RS_SET=ubuntu-1404-x64-docker bundle exec rake acceptance
