---
sudo: false

cache: bundler

language: ruby

bundler_args: --without development

env:
  - PUPPET_GEM_VERSION=3.1.1
  - PUPPET_GEM_VERSION=3.2.4
  - PUPPET_GEM_VERSION=3.3.2
  - PUPPET_GEM_VERSION=3.4.3
  - PUPPET_GEM_VERSION=3.5.1
  - PUPPET_GEM_VERSION=3.6.2
  - PUPPET_GEM_VERSION=3.7.0
  - PUPPET_GEM_VERSION=4.1.0

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.5
script: 
  - bundle exec rake test
