---
sudo: required

services:
  - docker

language: ruby

bundler_args: --without development

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.5
script: 
  - bundle exec rake test
  - RS_SET=ubuntu-1404-x64-docker bundle exec rake acceptance
  - RS_SET=debian-7-x64-docker bundle exec rake acceptance
