name          'endocode-ejabberd'
version       '0.1.0'
source        'UNKNOWN'
author        'endocode'
license       'Apache License, Version 2.0'
summary       'UNKNOWN'
description   'UNKNOWN'
project_page  'UNKNOWN'
